spring:
  batch:
    job:
      names: ${job.name:NONE}

---

spring:
  datasource:
    url: jdbc:oracle:thin:@1.235.70.245:1521:NEODB
    username: YOUTUBE
    password: youtube
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database: oracle
    database-platform: org.hibernate.dialect.Oracle12cDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  batch:
    jdbc:
      initialize-schema: always

youtube:
  api-key: AIzaSyAP4rwqb-luIUghDusPujwely5sPCWq3RU

logging:
  level:
    sql: debug